name: python_class
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libmpdec=4.0.0=h46256e1_0
  - libopenblas=0.3.29=h3f8574a_0
  - llvm-openmp=19.1.7=h5048363_2
  - ncurses=6.5=h923df54_0
  - numpy=2.3.1=py313h1a2ec72_0
  - numpy-base=2.3.1=py313hce0bb57_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.2=pyhc872135_1
  - python=3.13.5=h81a7116_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.3=h49f2429_0
  - setuptools=72.1.0=py313hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
prefix: /opt/miniconda3/envs/python_class
